import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Navbar from "@/app/components/layout/navbar";
import {
	setCulture,
	registerLicense,
	setCurrencyCode,
} from "@syncfusion/ej2-base";

const inter = Inter({ subsets: ["latin"] });

setCurrencyCode("GBP");
setCulture("en-UK");

registerLicense(
	"Ngo9BigBOggjHTQxAR8/V1NGaF1cWGhIfEx1RHxQdld5ZFRHallYTnNWUj0eQnxTdEZjUX5YcHNXQmFeV0JzVw=="
);

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className} suppressHydrationWarning={true}>
				<Providers>
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	);
}
